/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Setting;

import hospital_managment_system.Home;
import hospital_managment_system.Log_In;
import hospital_managment_system.MySqlConnect;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nafiul Alam
 */
public class nurse_setting extends javax.swing.JFrame {
  private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    /**
     * Creates new form nurse_setting
     */
    public nurse_setting() {
        initComponents();
        fetch_table();
    }
    private void fetch_table(){
        try{
            conn = (com.mysql.jdbc.Connection) MySqlConnect.ConnectDB();
            String sql = "SELECT * FROM log_in";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            doctor_setting_table.setModel(DbUtils.resultSetToTableModel(rs));
            doctor_setting_table.setAutoResizeMode(doctor_setting_table.AUTO_RESIZE_OFF);
            doctor_setting_table.getColumnModel().getColumn(0).setPreferredWidth(266);
            doctor_setting_table.getColumnModel().getColumn(1).setPreferredWidth(266);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void update_table(){
        try{
            String sql = "SELECT * FROM log_in";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            doctor_setting_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void clear(){
        userName_txt.setText("");
        password_txt.setText("");
    }
    public void clear2(){
        userName_txt1.setText("");
        password_txt1.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nurse_setting = new javax.swing.JPanel();
        id_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        save_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        userName_txt1 = new javax.swing.JTextField();
        password_txt1 = new javax.swing.JTextField();
        password_txt = new javax.swing.JTextField();
        userName_txt = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctor_setting_table = new javax.swing.JTable();
        back_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        bradcum_label = new javax.swing.JLabel();
        cover_laboratorist = new javax.swing.JLabel();
        bg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nurse Setting");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        nurse_setting.setPreferredSize(new java.awt.Dimension(1050, 626));
        nurse_setting.setLayout(null);

        id_label.setBackground(new java.awt.Color(255, 255, 255));
        id_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id_label.setForeground(new java.awt.Color(0, 51, 51));
        id_label.setText("User Name :");
        nurse_setting.add(id_label);
        id_label.setBounds(50, 250, 210, 40);

        name_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name_label.setForeground(new java.awt.Color(0, 51, 51));
        name_label.setText("Password :");
        nurse_setting.add(name_label);
        name_label.setBounds(50, 330, 150, 40);

        save_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save_btn.setForeground(new java.awt.Color(102, 102, 102));
        save_btn.setText("Save");
        save_btn.setToolTipText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        nurse_setting.add(save_btn);
        save_btn.setBounds(210, 420, 150, 60);

        clear_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(102, 102, 102));
        clear_btn.setText("Clear");
        clear_btn.setToolTipText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        nurse_setting.add(clear_btn);
        clear_btn.setBounds(50, 420, 150, 60);

        userName_txt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userName_txt1.setForeground(new java.awt.Color(102, 102, 102));
        nurse_setting.add(userName_txt1);
        userName_txt1.setBounds(500, 100, 270, 40);

        password_txt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password_txt1.setForeground(new java.awt.Color(102, 102, 102));
        nurse_setting.add(password_txt1);
        password_txt1.setBounds(770, 100, 270, 40);

        password_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password_txt.setForeground(new java.awt.Color(102, 102, 102));
        nurse_setting.add(password_txt);
        password_txt.setBounds(50, 370, 310, 40);

        userName_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userName_txt.setForeground(new java.awt.Color(102, 102, 102));
        userName_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userName_txtKeyPressed(evt);
            }
        });
        nurse_setting.add(userName_txt);
        userName_txt.setBounds(50, 290, 310, 40);

        delete_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(102, 102, 102));
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        nurse_setting.add(delete_btn);
        delete_btn.setBounds(710, 420, 160, 60);

        update_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update_btn.setForeground(new java.awt.Color(102, 102, 102));
        update_btn.setText("Update");
        update_btn.setToolTipText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        nurse_setting.add(update_btn);
        update_btn.setBounds(880, 420, 160, 60);

        doctor_setting_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doctor_setting_table.setForeground(new java.awt.Color(102, 102, 102));
        doctor_setting_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        doctor_setting_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctor_setting_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doctor_setting_table);

        nurse_setting.add(jScrollPane1);
        jScrollPane1.setBounds(500, 140, 540, 270);

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(102, 102, 102));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        nurse_setting.add(back_btn);
        back_btn.setBounds(560, 10, 160, 60);

        home_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(102, 102, 102));
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        nurse_setting.add(home_btn);
        home_btn.setBounds(720, 10, 160, 60);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOut_btn.setForeground(new java.awt.Color(102, 102, 102));
        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        nurse_setting.add(logOut_btn);
        logOut_btn.setBounds(880, 10, 160, 60);

        bradcum_label.setBackground(new java.awt.Color(153, 153, 153));
        bradcum_label.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 24)); // NOI18N
        bradcum_label.setForeground(new java.awt.Color(51, 51, 51));
        bradcum_label.setText("Setting Panel >> Nurse Setting");
        nurse_setting.add(bradcum_label);
        bradcum_label.setBounds(10, 0, 540, 70);

        cover_laboratorist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Patient/cover-photo.jpg"))); // NOI18N
        nurse_setting.add(cover_laboratorist);
        cover_laboratorist.setBounds(0, 0, 1050, 70);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/0549.jpg_wh1200.jpg"))); // NOI18N
        bg_label.setPreferredSize(new java.awt.Dimension(1050, 626));
        nurse_setting.add(bg_label);
        bg_label.setBounds(0, 0, 1050, 626);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nurse_setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nurse_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        conn = (com.mysql.jdbc.Connection) MySqlConnect.ConnectDB();
        if(conn != null){
            String userName = userName_txt.getText();
            String password = password_txt.getText();
            String sql = "INSERT INTO `log_in` (`UserName`, `Password`) VALUES (?, ?)";
            try{
                pst = conn.prepareStatement(sql);
                pst.setString(1, userName);
                pst.setString(2, password);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Saved Successfully!");

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        clear();
        update_table();
        doctor_setting_table.setAutoResizeMode(doctor_setting_table.AUTO_RESIZE_OFF);
        doctor_setting_table.getColumnModel().getColumn(0).setPreferredWidth(266);
        doctor_setting_table.getColumnModel().getColumn(1).setPreferredWidth(266);
    }//GEN-LAST:event_save_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        userName_txt.setText("");
        password_txt.setText("");
    }//GEN-LAST:event_clear_btnActionPerformed

    private void userName_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userName_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            password_txt.requestFocus();
        }
    }//GEN-LAST:event_userName_txtKeyPressed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        conn = (com.mysql.jdbc.Connection) MySqlConnect.ConnectDB();
        String sql = "DELETE FROM log_in WHERE Password = ?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, password_txt1.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
            pst.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        update_table();
        doctor_setting_table.setAutoResizeMode(doctor_setting_table.AUTO_RESIZE_OFF);
        doctor_setting_table.getColumnModel().getColumn(0).setPreferredWidth(266);
        doctor_setting_table.getColumnModel().getColumn(1).setPreferredWidth(266);
        clear2();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        try{
            conn = (com.mysql.jdbc.Connection) MySqlConnect.ConnectDB();
            String userName = userName_txt1.getText();
            String password = password_txt1.getText();

            String sql = "UPDATE `log_in` SET `UserName` = '"+userName+"', `Password` = '"+password+"' WHERE `log_in`.`Password` = '"+password+"'";

            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated Successfully");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        update_table();
        doctor_setting_table.setAutoResizeMode(doctor_setting_table.AUTO_RESIZE_OFF);
        doctor_setting_table.getColumnModel().getColumn(0).setPreferredWidth(266);
        doctor_setting_table.getColumnModel().getColumn(1).setPreferredWidth(266);
    }//GEN-LAST:event_update_btnActionPerformed

    private void doctor_setting_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctor_setting_tableMouseClicked
        try{
            conn = (com.mysql.jdbc.Connection) MySqlConnect.ConnectDB();
            int row = doctor_setting_table.getSelectedRow();
            String tableClick = (doctor_setting_table.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM log_in WHERE Password = '" + tableClick + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String userName = rs.getString("UserName");
                userName_txt1.setText(userName);
                String password = rs.getString("Password");
                password_txt1.setText(password);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_doctor_setting_tableMouseClicked

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        setting s=new setting();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        Log_In l=new Log_In();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nurse_setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nurse_setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nurse_setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nurse_setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nurse_setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel bg_label;
    private javax.swing.JLabel bradcum_label;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel cover_laboratorist;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTable doctor_setting_table;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel id_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JLabel name_label;
    private javax.swing.JPanel nurse_setting;
    private javax.swing.JTextField password_txt;
    private javax.swing.JTextField password_txt1;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton update_btn;
    private javax.swing.JTextField userName_txt;
    private javax.swing.JTextField userName_txt1;
    // End of variables declaration//GEN-END:variables
}
