/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Setting;

import hospital_managment_system.Home;
import hospital_managment_system.Log_In;

/**
 *
 * @author Nafiul Alam
 */
public class setting extends javax.swing.JFrame {

    /**
     * Creates new form setting
     */
    public setting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setting_panel = new javax.swing.JPanel();
        lab_icon = new javax.swing.JLabel();
        nicon = new javax.swing.JLabel();
        receptionist_i = new javax.swing.JLabel();
        D_icon = new javax.swing.JLabel();
        reception_setting_btn = new javax.swing.JButton();
        lab_setting_btn = new javax.swing.JButton();
        nurse_setting_btn = new javax.swing.JButton();
        doc_setting_btn = new javax.swing.JButton();
        logo_label = new javax.swing.JLabel();
        bradcum_label = new javax.swing.JLabel();
        clock_label = new javax.swing.JLabel();
        curr_time_label = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        cover_laboratorist = new javax.swing.JLabel();
        background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setting");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        setting_panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        setting_panel.setLayout(null);

        lab_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/Lab-icon.png"))); // NOI18N
        setting_panel.add(lab_icon);
        lab_icon.setBounds(740, 360, 32, 40);

        nicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/Nurse-icon.png"))); // NOI18N
        setting_panel.add(nicon);
        nicon.setBounds(740, 150, 32, 40);

        receptionist_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/receptionist.png"))); // NOI18N
        setting_panel.add(receptionist_i);
        receptionist_i.setBounds(290, 360, 32, 40);

        D_icon.setBackground(new java.awt.Color(204, 204, 204));
        D_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/Doctor-.png"))); // NOI18N
        setting_panel.add(D_icon);
        D_icon.setBounds(280, 150, 30, 40);

        reception_setting_btn.setBackground(new java.awt.Color(153, 153, 153));
        reception_setting_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 24)); // NOI18N
        reception_setting_btn.setForeground(new java.awt.Color(51, 51, 51));
        reception_setting_btn.setText("Reception Setting");
        reception_setting_btn.setToolTipText("Reception Setting");
        reception_setting_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reception_setting_btnActionPerformed(evt);
            }
        });
        setting_panel.add(reception_setting_btn);
        reception_setting_btn.setBounds(110, 340, 390, 160);

        lab_setting_btn.setBackground(new java.awt.Color(153, 153, 153));
        lab_setting_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 24)); // NOI18N
        lab_setting_btn.setForeground(new java.awt.Color(51, 51, 51));
        lab_setting_btn.setText("LAB Setting");
        lab_setting_btn.setToolTipText("LAB Setting");
        lab_setting_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lab_setting_btnActionPerformed(evt);
            }
        });
        setting_panel.add(lab_setting_btn);
        lab_setting_btn.setBounds(570, 340, 390, 160);

        nurse_setting_btn.setBackground(new java.awt.Color(153, 153, 153));
        nurse_setting_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 24)); // NOI18N
        nurse_setting_btn.setForeground(new java.awt.Color(51, 51, 51));
        nurse_setting_btn.setText("Nurse Setting");
        nurse_setting_btn.setToolTipText("Nurse Setting");
        nurse_setting_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurse_setting_btnActionPerformed(evt);
            }
        });
        setting_panel.add(nurse_setting_btn);
        nurse_setting_btn.setBounds(570, 130, 390, 160);

        doc_setting_btn.setBackground(new java.awt.Color(153, 153, 153));
        doc_setting_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 24)); // NOI18N
        doc_setting_btn.setForeground(new java.awt.Color(51, 51, 51));
        doc_setting_btn.setText("Doctor Setting");
        doc_setting_btn.setToolTipText("Doctor Setting");
        doc_setting_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_setting_btnActionPerformed(evt);
            }
        });
        setting_panel.add(doc_setting_btn);
        doc_setting_btn.setBounds(110, 130, 390, 160);
        setting_panel.add(logo_label);
        logo_label.setBounds(30, 20, 60, 50);

        bradcum_label.setFont(new java.awt.Font("BatmanForeverAlternate", 1, 24)); // NOI18N
        bradcum_label.setForeground(new java.awt.Color(51, 51, 51));
        bradcum_label.setText("Setting Panel");
        setting_panel.add(bradcum_label);
        bradcum_label.setBounds(90, 20, 260, 40);
        setting_panel.add(clock_label);
        clock_label.setBounds(430, 20, 0, 50);

        curr_time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        curr_time_label.setForeground(new java.awt.Color(51, 51, 51));
        setting_panel.add(curr_time_label);
        curr_time_label.setBounds(480, 30, 160, 40);

        home_btn.setBackground(new java.awt.Color(153, 153, 153));
        home_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(51, 51, 51));
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        setting_panel.add(home_btn);
        home_btn.setBounds(720, 20, 160, 27);

        logOut_btn.setBackground(new java.awt.Color(153, 153, 153));
        logOut_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 18)); // NOI18N
        logOut_btn.setForeground(new java.awt.Color(51, 51, 51));
        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        setting_panel.add(logOut_btn);
        logOut_btn.setBounds(880, 20, 160, 27);

        cover_laboratorist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Patient/cover-photo.jpg"))); // NOI18N
        setting_panel.add(cover_laboratorist);
        cover_laboratorist.setBounds(0, 0, 1050, 70);

        background_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/0549.jpg_wh1200.jpg"))); // NOI18N
        background_label.setPreferredSize(new java.awt.Dimension(1050, 626));
        setting_panel.add(background_label);
        background_label.setBounds(0, 0, 1050, 626);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(setting_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(setting_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reception_setting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reception_setting_btnActionPerformed
        reception_setting rs=new reception_setting();
        rs.setVisible(true);
        dispose();
    }//GEN-LAST:event_reception_setting_btnActionPerformed

    private void lab_setting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lab_setting_btnActionPerformed
        lab_setting rs=new lab_setting();
        rs.setVisible(true);
        dispose();
    }//GEN-LAST:event_lab_setting_btnActionPerformed

    private void nurse_setting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurse_setting_btnActionPerformed
        nurse_setting ns=new nurse_setting();
        ns.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_nurse_setting_btnActionPerformed

    private void doc_setting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_setting_btnActionPerformed
        
        doctor_setting ds=new doctor_setting();
        ds.setVisible(true);
        dispose();
    }//GEN-LAST:event_doc_setting_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        Log_In l=new Log_In();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel D_icon;
    private javax.swing.JLabel background_label;
    private javax.swing.JLabel bradcum_label;
    private javax.swing.JLabel clock_label;
    private javax.swing.JLabel cover_laboratorist;
    private javax.swing.JLabel curr_time_label;
    private javax.swing.JButton doc_setting_btn;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel lab_icon;
    private javax.swing.JButton lab_setting_btn;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JLabel logo_label;
    private javax.swing.JLabel nicon;
    private javax.swing.JButton nurse_setting_btn;
    private javax.swing.JButton reception_setting_btn;
    private javax.swing.JLabel receptionist_i;
    private javax.swing.JPanel setting_panel;
    // End of variables declaration//GEN-END:variables
}
