/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_managment_system;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nafiul Alam
 */
public class ChoosePatientPage extends javax.swing.JFrame {
    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    DefaultTableModel defaultTableModel = new DefaultTableModel();
    
    String DoctorName;

    /**
     * Creates new form ChoosePatientPage
     */
    public ChoosePatientPage() {
        initComponents();
        Object columns[] = {"Serial", "ID", "Date", "Name", "Age", "Disease", "Phone", "Email", "Address", "Gender", "Romm", "BG", "Status"};
        defaultTableModel.setColumnIdentifiers(columns);
        patient_table.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choose_patient_panel = new javax.swing.JPanel();
        back_btn = new javax.swing.JButton();
        view_btn2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patient_table = new javax.swing.JTable();
        search_txt = new javax.swing.JTextField();
        page_title_label = new javax.swing.JLabel();
        time_label = new javax.swing.JLabel();
        curr_time_label = new javax.swing.JLabel();
        search_btn = new javax.swing.JButton();
        department_label = new javax.swing.JLabel();
        department_label1 = new javax.swing.JLabel();
        appointment_btn = new javax.swing.JButton();
        background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Patient Page");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        choose_patient_panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        choose_patient_panel.setLayout(null);

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(102, 102, 102));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        choose_patient_panel.add(back_btn);
        back_btn.setBounds(10, 530, 160, 60);

        view_btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_btn2.setForeground(new java.awt.Color(102, 102, 102));
        view_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btn2ActionPerformed(evt);
            }
        });
        choose_patient_panel.add(view_btn2);
        view_btn2.setBounds(950, 90, 90, 60);

        patient_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(patient_table);

        choose_patient_panel.add(jScrollPane1);
        jScrollPane1.setBounds(2, 152, 1040, 370);

        search_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search_txt.setForeground(new java.awt.Color(102, 102, 102));
        choose_patient_panel.add(search_txt);
        search_txt.setBounds(440, 90, 360, 60);

        page_title_label.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 26)); // NOI18N
        page_title_label.setForeground(new java.awt.Color(255, 255, 255));
        page_title_label.setText("Set Appointment Panel >> Choose Doctor");
        choose_patient_panel.add(page_title_label);
        page_title_label.setBounds(20, 20, 590, 60);

        time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        time_label.setForeground(new java.awt.Color(102, 102, 102));
        choose_patient_panel.add(time_label);
        time_label.setBounds(810, 30, 60, 50);

        curr_time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        curr_time_label.setForeground(new java.awt.Color(102, 102, 102));
        choose_patient_panel.add(curr_time_label);
        curr_time_label.setBounds(870, 40, 170, 40);

        search_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search_btn.setForeground(new java.awt.Color(102, 102, 102));
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        choose_patient_panel.add(search_btn);
        search_btn.setBounds(800, 90, 150, 60);

        department_label.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        department_label.setForeground(new java.awt.Color(102, 102, 102));
        department_label.setText("Choose Patient's Name or ID >>");
        choose_patient_panel.add(department_label);
        department_label.setBounds(20, 90, 430, 60);

        department_label1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        department_label1.setForeground(new java.awt.Color(102, 102, 102));
        department_label1.setText("Click Appointment Button For  Appointment");
        choose_patient_panel.add(department_label1);
        department_label1.setBounds(250, 530, 570, 60);

        appointment_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        appointment_btn.setForeground(new java.awt.Color(102, 102, 102));
        appointment_btn.setText("Appointment");
        appointment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointment_btnActionPerformed(evt);
            }
        });
        choose_patient_panel.add(appointment_btn);
        appointment_btn.setBounds(840, 530, 200, 60);
        choose_patient_panel.add(background_label);
        background_label.setBounds(0, 0, 1050, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(choose_patient_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(choose_patient_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        ChooseDoctorPage lhp = new ChooseDoctorPage();
        lhp.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void view_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btn2ActionPerformed
        
    }//GEN-LAST:event_view_btn2ActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        conn=MySqlConnect.ConnectDB();
        defaultTableModel.getDataVector().removeAllElements();
        defaultTableModel.fireTableDataChanged();
        String searchKey = search_txt.getText();
        String sql = " SELECT `Serial`, `ID`, `Date`, `Name`, `Age`, `Disease`, `Phone`, `Email`, `Address`, `Gender`, `Room`, `BG`, `Status` from patient where `Name` = '" + searchKey + "'";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Object columnData[] = new Object[13];
            while (rs.next()) {
                columnData[0] = rs.getString("Serial");
                columnData[1] = rs.getString("ID");
                columnData[2] = rs.getString("Date");
                columnData[3] = rs.getString("Name");
                columnData[4] = rs.getInt("Age");
                columnData[5] = rs.getString("Disease");
                columnData[6] = rs.getString("Phone");
                columnData[7] = rs.getString("Email");
                columnData[8] = rs.getString("Address");
                columnData[9] = rs.getString("Gender");
                columnData[10] = rs.getString("Room");
                columnData[11] = rs.getString("BG");
                columnData[12] = rs.getString("Status");
                defaultTableModel.addRow(columnData);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_search_btnActionPerformed

    private void appointment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointment_btnActionPerformed
        int row = patient_table.getSelectedRow();
        String pname = (patient_table.getValueAt(row, 3).toString());
       conn=MySqlConnect.ConnectDB();
        String sql = "insert into appointment(DoctorName, PatientName) values (?,?)";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, DoctorName);
            pst.setString(2, pname);
            pst.execute();
            JOptionPane.showMessageDialog(null, "PATIENT " + pname + " Appointmented with DOCTOR " + DoctorName);
        } catch (HeadlessException | SQLException e) {
        }
    }//GEN-LAST:event_appointment_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoosePatientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoosePatientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoosePatientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoosePatientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoosePatientPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointment_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel background_label;
    private javax.swing.JPanel choose_patient_panel;
    private javax.swing.JLabel curr_time_label;
    private javax.swing.JLabel department_label;
    private javax.swing.JLabel department_label1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel page_title_label;
    private javax.swing.JTable patient_table;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JLabel time_label;
    private javax.swing.JButton view_btn2;
    // End of variables declaration//GEN-END:variables
}
