/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_managment_system;

/**
 *
 * @author Nafiul Alam
 */
public class doctor_mainpage extends javax.swing.JFrame {

    /**
     *
     */
    public doctor_mainpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Calendar = new com.toedter.calendar.JCalendar();
        Appointment_btn = new javax.swing.JButton();
        view_appointment = new javax.swing.JButton();
        page_title_label = new javax.swing.JLabel();
        time_label = new javax.swing.JLabel();
        curr_time_label = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        cover_patient = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Doctor Main");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 626));
        jPanel1.setLayout(null);

        Calendar.setBackground(new java.awt.Color(255, 255, 255));
        Calendar.setForeground(new java.awt.Color(153, 153, 153));
        Calendar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel1.add(Calendar);
        Calendar.setBounds(420, 310, 620, 290);

        Appointment_btn.setBackground(new java.awt.Color(204, 204, 255));
        Appointment_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Appointment_btn.setForeground(new java.awt.Color(102, 102, 102));
        Appointment_btn.setText("Appointment");
        Appointment_btn.setToolTipText("Appointment");
        Appointment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Appointment_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Appointment_btn);
        Appointment_btn.setBounds(20, 280, 180, 60);

        view_appointment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        view_appointment.setForeground(new java.awt.Color(102, 102, 102));
        view_appointment.setText("View Appointment");
        view_appointment.setToolTipText("View Appointment");
        view_appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_appointmentActionPerformed(evt);
            }
        });
        jPanel1.add(view_appointment);
        view_appointment.setBounds(570, 100, 460, 180);

        page_title_label.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 30)); // NOI18N
        page_title_label.setForeground(new java.awt.Color(51, 51, 51));
        page_title_label.setText("Doctor Panel >> View Appointment");
        jPanel1.add(page_title_label);
        page_title_label.setBounds(20, 20, 730, 70);

        time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        time_label.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(time_label);
        time_label.setBounds(20, 220, 60, 50);

        curr_time_label.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        curr_time_label.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(curr_time_label);
        curr_time_label.setBounds(80, 230, 170, 40);

        logout_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(102, 102, 102));
        logout_btn.setText("LogOut");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        jPanel1.add(logout_btn);
        logout_btn.setBounds(880, 10, 85, 60);

        cover_patient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Patient/cover-photo.jpg"))); // NOI18N
        jPanel1.add(cover_patient);
        cover_patient.setBounds(0, 0, 1050, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/bg_home.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Appointment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Appointment_btnActionPerformed
        ViewAppointment cdp = new ViewAppointment();
        cdp.setVisible(true);
        dispose();
    }//GEN-LAST:event_Appointment_btnActionPerformed

    private void view_appointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_appointmentActionPerformed
        ViewAppointment cdp = new ViewAppointment();
        cdp.setVisible(true);
        dispose();
    }//GEN-LAST:event_view_appointmentActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        Log_In l=new Log_In();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctor_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctor_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctor_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctor_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctor_mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Appointment_btn;
    private com.toedter.calendar.JCalendar Calendar;
    private javax.swing.JLabel cover_patient;
    private javax.swing.JLabel curr_time_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JLabel page_title_label;
    private javax.swing.JLabel time_label;
    private javax.swing.JButton view_appointment;
    // End of variables declaration//GEN-END:variables
}
