/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_managment_system;

import Nurse.Nurse;
import Patient.patient;
import Receptionist.Receptionist_panel;
import Setting.setting;
import doctor.doctor;
import laboratorist.laboratorist;


/**
 *
 * @author Nafiul Alam
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home_Panel = new javax.swing.JPanel();
        Calendar = new com.toedter.calendar.JCalendar();
        ab_icon = new javax.swing.JLabel();
        about_us = new javax.swing.JButton();
        s_icon = new javax.swing.JLabel();
        setting = new javax.swing.JButton();
        lab_icon = new javax.swing.JLabel();
        laboratorist = new javax.swing.JButton();
        p_icon = new javax.swing.JLabel();
        patient = new javax.swing.JButton();
        nicon = new javax.swing.JLabel();
        nurse = new javax.swing.JButton();
        LOGout = new javax.swing.JLabel();
        log_out = new javax.swing.JButton();
        receptionist_i = new javax.swing.JLabel();
        receptionist = new javax.swing.JButton();
        D_icon = new javax.swing.JLabel();
        Doctor = new javax.swing.JButton();
        H_name = new javax.swing.JLabel();
        H_Icon = new javax.swing.JLabel();
        Home_heading = new javax.swing.JLabel();
        cover = new javax.swing.JLabel();
        HomeBG_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Window");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        Home_Panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        Home_Panel.setLayout(null);

        Calendar.setBackground(new java.awt.Color(255, 255, 255));
        Calendar.setForeground(new java.awt.Color(153, 153, 153));
        Calendar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Home_Panel.add(Calendar);
        Calendar.setBounds(210, 280, 620, 290);

        ab_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/about-icon.png"))); // NOI18N
        Home_Panel.add(ab_icon);
        ab_icon.setBounds(20, 470, 32, 40);

        about_us.setBackground(new java.awt.Color(153, 153, 153));
        about_us.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 12)); // NOI18N
        about_us.setForeground(new java.awt.Color(51, 51, 51));
        about_us.setText("about us");
        about_us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_usActionPerformed(evt);
            }
        });
        Home_Panel.add(about_us);
        about_us.setBounds(0, 460, 210, 60);

        s_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/Settings-icon.png"))); // NOI18N
        Home_Panel.add(s_icon);
        s_icon.setBounds(20, 410, 32, 40);

        setting.setBackground(new java.awt.Color(153, 153, 153));
        setting.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 12)); // NOI18N
        setting.setForeground(new java.awt.Color(51, 51, 51));
        setting.setText("setting");
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });
        Home_Panel.add(setting);
        setting.setBounds(0, 400, 210, 60);

        lab_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/Lab-icon.png"))); // NOI18N
        Home_Panel.add(lab_icon);
        lab_icon.setBounds(10, 350, 32, 40);

        laboratorist.setBackground(new java.awt.Color(153, 153, 153));
        laboratorist.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 12)); // NOI18N
        laboratorist.setForeground(new java.awt.Color(51, 51, 51));
        laboratorist.setText("laboratorist");
        laboratorist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratoristActionPerformed(evt);
            }
        });
        Home_Panel.add(laboratorist);
        laboratorist.setBounds(0, 340, 210, 60);

        p_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/Patient-icon.png"))); // NOI18N
        Home_Panel.add(p_icon);
        p_icon.setBounds(20, 290, 32, 40);

        patient.setBackground(new java.awt.Color(153, 153, 153));
        patient.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 12)); // NOI18N
        patient.setForeground(new java.awt.Color(51, 51, 51));
        patient.setText("patient");
        patient.setPreferredSize(new java.awt.Dimension(91, 21));
        patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientActionPerformed(evt);
            }
        });
        Home_Panel.add(patient);
        patient.setBounds(0, 280, 210, 60);

        nicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/Nurse-icon.png"))); // NOI18N
        Home_Panel.add(nicon);
        nicon.setBounds(20, 230, 32, 40);

        nurse.setBackground(new java.awt.Color(153, 153, 153));
        nurse.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 12)); // NOI18N
        nurse.setForeground(new java.awt.Color(51, 51, 51));
        nurse.setText("nurse");
        nurse.setPreferredSize(new java.awt.Dimension(91, 21));
        nurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseActionPerformed(evt);
            }
        });
        Home_Panel.add(nurse);
        nurse.setBounds(0, 210, 210, 70);

        LOGout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/system-log-out-icon.png"))); // NOI18N
        Home_Panel.add(LOGout);
        LOGout.setBounds(20, 520, 30, 50);

        log_out.setBackground(new java.awt.Color(153, 153, 153));
        log_out.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 11)); // NOI18N
        log_out.setForeground(new java.awt.Color(51, 51, 51));
        log_out.setText("log-out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        Home_Panel.add(log_out);
        log_out.setBounds(0, 520, 210, 50);

        receptionist_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/receptionist.png"))); // NOI18N
        Home_Panel.add(receptionist_i);
        receptionist_i.setBounds(20, 150, 32, 40);

        receptionist.setBackground(new java.awt.Color(153, 153, 153));
        receptionist.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 12)); // NOI18N
        receptionist.setForeground(new java.awt.Color(51, 51, 51));
        receptionist.setText("Receptionist");
        receptionist.setPreferredSize(new java.awt.Dimension(91, 21));
        receptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionistActionPerformed(evt);
            }
        });
        Home_Panel.add(receptionist);
        receptionist.setBounds(0, 140, 210, 70);

        D_icon.setBackground(new java.awt.Color(204, 204, 204));
        D_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/Doctor-.png"))); // NOI18N
        Home_Panel.add(D_icon);
        D_icon.setBounds(20, 90, 30, 40);

        Doctor.setBackground(new java.awt.Color(153, 153, 153));
        Doctor.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 12)); // NOI18N
        Doctor.setForeground(new java.awt.Color(51, 51, 51));
        Doctor.setText("Doctor");
        Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorActionPerformed(evt);
            }
        });
        Home_Panel.add(Doctor);
        Doctor.setBounds(0, 70, 210, 70);

        H_name.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        H_name.setForeground(new java.awt.Color(204, 204, 0));
        H_name.setText("Life Hospital");
        Home_Panel.add(H_name);
        H_name.setBounds(60, 20, 110, 30);

        H_Icon.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        H_Icon.setForeground(new java.awt.Color(51, 153, 0));
        H_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/hospital-icon.png"))); // NOI18N
        Home_Panel.add(H_Icon);
        H_Icon.setBounds(10, 0, 48, 70);

        Home_heading.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 24)); // NOI18N
        Home_heading.setForeground(new java.awt.Color(51, 51, 51));
        Home_heading.setText("HOSPITAL MANAGMENT SYSTEM");
        Home_Panel.add(Home_heading);
        Home_heading.setBounds(280, 10, 490, 40);

        cover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/cover-photo.jpg"))); // NOI18N
        cover.setText("jLabel1");
        Home_Panel.add(cover);
        cover.setBounds(0, 0, 1050, 70);

        HomeBG_Label.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        HomeBG_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/bc.jpg"))); // NOI18N
        HomeBG_Label.setToolTipText("");
        HomeBG_Label.setPreferredSize(new java.awt.Dimension(1050, 626));
        Home_Panel.add(HomeBG_Label);
        HomeBG_Label.setBounds(0, 0, 1050, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Home_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        Home_Panel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorActionPerformed
      
        doctor d=new doctor();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_DoctorActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed

        Log_In l=new Log_In();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_log_outActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
        setting s=new setting();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_settingActionPerformed

    private void receptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionistActionPerformed
        // TODO add your handling code here:
        Receptionist_panel rp=new Receptionist_panel();
        rp.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_receptionistActionPerformed

    private void nurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseActionPerformed
        // TODO add your handling code here:
        Nurse n=new Nurse();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_nurseActionPerformed

    private void patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientActionPerformed
        // TODO add your handling code here:
        patient p=new patient();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_patientActionPerformed

    private void laboratoristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratoristActionPerformed
        // TODO add your handling code here:
        laboratorist l=new laboratorist();
        l.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_laboratoristActionPerformed

    private void about_usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_about_usActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calendar;
    private javax.swing.JLabel D_icon;
    private javax.swing.JButton Doctor;
    private javax.swing.JLabel H_Icon;
    private javax.swing.JLabel H_name;
    private javax.swing.JLabel HomeBG_Label;
    private javax.swing.JPanel Home_Panel;
    private javax.swing.JLabel Home_heading;
    private javax.swing.JLabel LOGout;
    private javax.swing.JLabel ab_icon;
    private javax.swing.JButton about_us;
    private javax.swing.JLabel cover;
    private javax.swing.JLabel lab_icon;
    private javax.swing.JButton laboratorist;
    private javax.swing.JButton log_out;
    private javax.swing.JLabel nicon;
    private javax.swing.JButton nurse;
    private javax.swing.JLabel p_icon;
    private javax.swing.JButton patient;
    private javax.swing.JButton receptionist;
    private javax.swing.JLabel receptionist_i;
    private javax.swing.JLabel s_icon;
    private javax.swing.JButton setting;
    // End of variables declaration//GEN-END:variables
}
