/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_managment_system;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Nafiul Alam
 */
public class Log_In extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form Log_In
     */
    public Log_In() {
        initComponents();
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg_Panel = new javax.swing.JPanel();
        lgin = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        LogIn_Button = new javax.swing.JButton();
        Password_Field = new javax.swing.JPasswordField();
        Name_field = new javax.swing.JTextField();
        Heading_label = new javax.swing.JLabel();
        Login_Label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log In Window");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        Bg_Panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        Bg_Panel.setLayout(null);

        lgin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/sign-check-icon.png"))); // NOI18N
        Bg_Panel.add(lgin);
        lgin.setBounds(590, 320, 30, 40);

        pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/password-icon.png"))); // NOI18N
        Bg_Panel.add(pass);
        pass.setBounds(370, 260, 40, 40);

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/Users-icon.png"))); // NOI18N
        Bg_Panel.add(User);
        User.setBounds(370, 200, 50, 50);

        LogIn_Button.setBackground(new java.awt.Color(153, 255, 204));
        LogIn_Button.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 12)); // NOI18N
        LogIn_Button.setForeground(new java.awt.Color(51, 51, 51));
        LogIn_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_ButtonActionPerformed(evt);
            }
        });
        Bg_Panel.add(LogIn_Button);
        LogIn_Button.setBounds(500, 320, 210, 40);

        Password_Field.setBackground(new java.awt.Color(204, 204, 204));
        Password_Field.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Password_Field.setForeground(new java.awt.Color(51, 51, 51));
        Password_Field.setPreferredSize(new java.awt.Dimension(6, 20));
        Password_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_FieldActionPerformed(evt);
            }
        });
        Bg_Panel.add(Password_Field);
        Password_Field.setBounds(430, 260, 340, 40);

        Name_field.setBackground(new java.awt.Color(204, 204, 204));
        Name_field.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Name_field.setForeground(new java.awt.Color(51, 51, 51));
        Name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_fieldActionPerformed(evt);
            }
        });
        Bg_Panel.add(Name_field);
        Name_field.setBounds(430, 200, 340, 40);

        Heading_label.setFont(new java.awt.Font("BatmanForeverAlternate", 1, 36)); // NOI18N
        Heading_label.setForeground(new java.awt.Color(51, 51, 51));
        Heading_label.setText("HOSPITAL MANAGMENT SYSTEM");
        Bg_Panel.add(Heading_label);
        Heading_label.setBounds(190, 100, 770, 40);

        Login_Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_system/0549.jpg_wh1200.jpg"))); // NOI18N
        Login_Label1.setText("jLabel1");
        Login_Label1.setPreferredSize(new java.awt.Dimension(1050, 626));
        Bg_Panel.add(Login_Label1);
        Login_Label1.setBounds(0, 0, 1050, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bg_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_fieldActionPerformed

    private void LogIn_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_ButtonActionPerformed
        
        conn=MySqlConnect.ConnectDB();
        String Sql="Select * from log_in where UserName=? and Password=? " ;
        try{
            pst=conn.prepareStatement(Sql);
            pst.setString(1,Name_field.getText());
            pst.setString(2,Password_Field.getText());
            rs=pst.executeQuery();
            if(rs.next()){
               if("admin".equals(Name_field.getText()) & "admin".equals(Password_Field.getText())){
                    Home h=new Home();
                    h.setVisible(true);
                    rs.close();
                    pst.close();
                    dispose();
               }
               if("doctor".equals(Name_field.getText()) & "doctor".equals(Password_Field.getText())){
                    doctor_mainpage d=new doctor_mainpage();
                    d.setVisible(true);
                    rs.close();
                    pst.close();
                    dispose();
               }
               if("recep".equals(Name_field.getText()) & "recep".equals(Password_Field.getText())){
                    Rep_mainpage r=new Rep_mainpage();
                    r.setVisible(true);
                    rs.close();
                    pst.close();
                    dispose();
               }
               

               
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid username or password","Access Denied",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
//        Home h=new Home();
//        h.setVisible(true);
    }//GEN-LAST:event_LogIn_ButtonActionPerformed

    private void Password_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg_Panel;
    private javax.swing.JLabel Heading_label;
    private javax.swing.JButton LogIn_Button;
    private javax.swing.JLabel Login_Label1;
    private javax.swing.JTextField Name_field;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JLabel User;
    private javax.swing.JLabel lgin;
    private javax.swing.JLabel pass;
    // End of variables declaration//GEN-END:variables
}
