/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nurse;

import com.mysql.jdbc.Connection;
import hospital_managment_system.Log_In;
import hospital_managment_system.Home;
import hospital_managment_system.MySqlConnect;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Nafiul Alam
 */
public class add_nurse extends javax.swing.JFrame {
    
    private Connection conn;
    private PreparedStatement pst;

    /**
     * Creates new form add_nurse
     */
    public add_nurse() {
        initComponents();
    }
    public void clear(){
        id_txt.setText("");
        name_txt.setText("");
        phone_txt.setText("");
        email_txt.setText("");
        age_txt.setText("");
        address_txt.setText("");
        Join_Date.setCalendar(null);
        gender_combox.setSelectedIndex(0);
        blood_combox.setSelectedIndex(0);
        status_combox.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_nurse = new javax.swing.JPanel();
        clear_i = new javax.swing.JLabel();
        save_icon = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        log_i = new javax.swing.JLabel();
        logOut_btn = new javax.swing.JButton();
        home_i = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();
        back_i = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        status_label = new javax.swing.JLabel();
        status_combox = new javax.swing.JComboBox<>();
        blood_label = new javax.swing.JLabel();
        blood_combox = new javax.swing.JComboBox<>();
        gender_label = new javax.swing.JLabel();
        gender_combox = new javax.swing.JComboBox<>();
        date_label = new javax.swing.JLabel();
        Join_Date = new com.toedter.calendar.JDateChooser();
        age_label = new javax.swing.JLabel();
        age_txt = new javax.swing.JTextField();
        address_label = new javax.swing.JLabel();
        address_txt = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        phone_label = new javax.swing.JLabel();
        phone_txt = new javax.swing.JTextField();
        name_label = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        bradcum_label = new javax.swing.JLabel();
        cover_nurse = new javax.swing.JLabel();
        bg_add = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Nurse");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        add_nurse.setPreferredSize(new java.awt.Dimension(1050, 626));
        add_nurse.setLayout(null);

        clear_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/clear-icon.png"))); // NOI18N
        add_nurse.add(clear_i);
        clear_i.setBounds(530, 470, 32, 40);

        save_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/save-icon.png"))); // NOI18N
        add_nurse.add(save_icon);
        save_icon.setBounds(690, 470, 32, 40);

        clear_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(102, 102, 102));
        clear_btn.setText("Clear");
        clear_btn.setToolTipText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        add_nurse.add(clear_btn);
        clear_btn.setBounds(530, 460, 150, 60);

        save_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save_btn.setForeground(new java.awt.Color(102, 102, 102));
        save_btn.setText("Save");
        save_btn.setToolTipText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        add_nurse.add(save_btn);
        save_btn.setBounds(680, 460, 150, 60);

        log_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/system-log-out-icon.png"))); // NOI18N
        add_nurse.add(log_i);
        log_i.setBounds(810, 100, 32, 50);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOut_btn.setForeground(new java.awt.Color(102, 102, 102));
        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        add_nurse.add(logOut_btn);
        logOut_btn.setBounds(800, 90, 160, 70);

        home_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/home-icon.png"))); // NOI18N
        add_nurse.add(home_i);
        home_i.setBounds(650, 100, 32, 50);

        home_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(102, 102, 102));
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        add_nurse.add(home_btn);
        home_btn.setBounds(640, 90, 160, 70);

        back_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/back-icon.png"))); // NOI18N
        add_nurse.add(back_i);
        back_i.setBounds(500, 100, 40, 50);

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(102, 102, 102));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        add_nurse.add(back_btn);
        back_btn.setBounds(480, 90, 160, 70);

        status_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        status_label.setForeground(new java.awt.Color(0, 51, 51));
        status_label.setText("Maritial Status :");
        add_nurse.add(status_label);
        status_label.setBounds(470, 410, 190, 40);

        status_combox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        status_combox.setForeground(new java.awt.Color(102, 102, 102));
        status_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", " " }));
        add_nurse.add(status_combox);
        status_combox.setBounds(670, 410, 155, 40);

        blood_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blood_label.setForeground(new java.awt.Color(204, 0, 0));
        blood_label.setText("Blood Group :");
        add_nurse.add(blood_label);
        blood_label.setBounds(500, 360, 164, 40);

        blood_combox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blood_combox.setForeground(new java.awt.Color(102, 102, 102));
        blood_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", " ", " " }));
        add_nurse.add(blood_combox);
        blood_combox.setBounds(670, 360, 155, 40);

        gender_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gender_label.setForeground(new java.awt.Color(0, 51, 51));
        gender_label.setText("Gender :");
        add_nurse.add(gender_label);
        gender_label.setBounds(560, 310, 102, 40);

        gender_combox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gender_combox.setForeground(new java.awt.Color(102, 102, 102));
        gender_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "FeMale", "Common", " " }));
        add_nurse.add(gender_combox);
        gender_combox.setBounds(670, 310, 155, 40);

        date_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date_label.setForeground(new java.awt.Color(0, 51, 51));
        date_label.setText("Join Date :");
        add_nurse.add(date_label);
        date_label.setBounds(530, 260, 140, 40);

        Join_Date.setDateFormatString("yyyy-MM-dd");
        Join_Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_nurse.add(Join_Date);
        Join_Date.setBounds(670, 260, 180, 40);

        age_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        age_label.setForeground(new java.awt.Color(0, 51, 51));
        age_label.setText("Age :");
        add_nurse.add(age_label);
        age_label.setBounds(600, 210, 70, 40);

        age_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        age_txt.setForeground(new java.awt.Color(51, 51, 51));
        age_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                age_txtKeyPressed(evt);
            }
        });
        add_nurse.add(age_txt);
        age_txt.setBounds(670, 210, 150, 40);

        address_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        address_label.setForeground(new java.awt.Color(0, 51, 51));
        address_label.setText("Address :");
        add_nurse.add(address_label);
        address_label.setBounds(30, 410, 110, 40);

        address_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        address_txt.setForeground(new java.awt.Color(51, 51, 51));
        address_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                address_txtKeyPressed(evt);
            }
        });
        add_nurse.add(address_txt);
        address_txt.setBounds(150, 410, 310, 40);

        email_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        email_label.setForeground(new java.awt.Color(0, 51, 51));
        email_label.setText("Email :");
        add_nurse.add(email_label);
        email_label.setBounds(60, 360, 90, 40);

        email_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_txt.setForeground(new java.awt.Color(51, 51, 51));
        email_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                email_txtKeyPressed(evt);
            }
        });
        add_nurse.add(email_txt);
        email_txt.setBounds(150, 360, 310, 40);

        phone_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        phone_label.setForeground(new java.awt.Color(0, 51, 51));
        phone_label.setText("Phone :");
        add_nurse.add(phone_label);
        phone_label.setBounds(50, 310, 100, 40);

        phone_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone_txt.setForeground(new java.awt.Color(51, 51, 51));
        phone_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phone_txtKeyPressed(evt);
            }
        });
        add_nurse.add(phone_txt);
        phone_txt.setBounds(150, 310, 310, 40);

        name_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name_label.setForeground(new java.awt.Color(0, 51, 51));
        name_label.setText("Name :");
        add_nurse.add(name_label);
        name_label.setBounds(60, 260, 90, 40);

        name_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name_txt.setForeground(new java.awt.Color(51, 51, 51));
        name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name_txtKeyPressed(evt);
            }
        });
        add_nurse.add(name_txt);
        name_txt.setBounds(150, 260, 310, 40);

        id_label.setBackground(new java.awt.Color(255, 255, 255));
        id_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id_label.setForeground(new java.awt.Color(0, 51, 51));
        id_label.setText("ID :");
        add_nurse.add(id_label);
        id_label.setBounds(100, 210, 50, 40);

        id_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id_txt.setForeground(new java.awt.Color(51, 51, 51));
        id_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_txtKeyPressed(evt);
            }
        });
        add_nurse.add(id_txt);
        id_txt.setBounds(150, 210, 310, 40);

        bradcum_label.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 30)); // NOI18N
        bradcum_label.setForeground(new java.awt.Color(51, 51, 51));
        bradcum_label.setText("Nurse Panel >> Add Nurse");
        add_nurse.add(bradcum_label);
        bradcum_label.setBounds(10, 0, 540, 70);

        cover_nurse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nurse/cover-photo.jpg"))); // NOI18N
        add_nurse.add(cover_nurse);
        cover_nurse.setBounds(0, 0, 1050, 70);

        bg_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nurse/bg_nurse.jpg"))); // NOI18N
        bg_add.setText("jLabel1");
        add_nurse.add(bg_add);
        bg_add.setBounds(0, 0, 1050, 626);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(add_nurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(add_nurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            name_txt.requestFocus();
        }
    }//GEN-LAST:event_id_txtKeyPressed

    private void name_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            phone_txt.requestFocus();
        }
    }//GEN-LAST:event_name_txtKeyPressed

    private void phone_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            email_txt.requestFocus();
        }
    }//GEN-LAST:event_phone_txtKeyPressed

    private void email_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            address_txt.requestFocus();
        }
    }//GEN-LAST:event_email_txtKeyPressed

    private void address_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_address_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            age_txt.requestFocus();
        }
    }//GEN-LAST:event_address_txtKeyPressed

    private void age_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_txtKeyPressed
        /*int key = evt.getKeyCode();
        if(key ==  10){
            department_combox.requestFocus();
        }*/
    }//GEN-LAST:event_age_txtKeyPressed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        Nurse n=new Nurse();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        // TODO add your handling code here:
        Log_In l=new Log_In();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        conn = (Connection) MySqlConnect.ConnectDB();
        if(conn != null){
            String id = id_txt.getText();
            String name = name_txt.getText();
            String phone = phone_txt.getText();
            String email = email_txt.getText();
            String address = address_txt.getText();
            int age = Integer.parseInt(age_txt.getText());
            String date = ((JTextField)Join_Date.getDateEditor().getUiComponent()).getText();
            String gender = (String) gender_combox.getSelectedItem();
            String blood = (String) blood_combox.getSelectedItem();
            String status = (String) status_combox.getSelectedItem();
            String sql = "INSERT INTO `nurse` (`ID`, `Name`,`Email`,  `Phone`, `Address`, `Age`, `Gender`, `Join Date`, `BG`, `Status`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            try{
                pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.setString(2, name);
                pst.setString(3, email);
                pst.setString(4, phone);
                pst.setString(5, address);
                pst.setInt(6, age);
                pst.setString(7, gender);
                pst.setString(8, date);
                pst.setString(9, blood);
                pst.setString(10, status);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Saved Successfully!");

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        clear();
        view_nurse vn = new view_nurse();
        vn.setVisible(true);
        dispose();
    }//GEN-LAST:event_save_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        id_txt.setText("");
        name_txt.setText("");
        phone_txt.setText("");
        email_txt.setText("");
        age_txt.setText("");
        address_txt.setText("");
        Join_Date.setCalendar(null);
        gender_combox.setSelectedIndex(0);
        blood_combox.setSelectedIndex(0);
        status_combox.setSelectedIndex(0);
    }//GEN-LAST:event_clear_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_nurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_nurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_nurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_nurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_nurse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Join_Date;
    private javax.swing.JPanel add_nurse;
    private javax.swing.JLabel address_label;
    private javax.swing.JTextField address_txt;
    private javax.swing.JLabel age_label;
    private javax.swing.JTextField age_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel back_i;
    private javax.swing.JLabel bg_add;
    private javax.swing.JComboBox<String> blood_combox;
    private javax.swing.JLabel blood_label;
    private javax.swing.JLabel bradcum_label;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel clear_i;
    private javax.swing.JLabel cover_nurse;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_txt;
    private javax.swing.JComboBox<String> gender_combox;
    private javax.swing.JLabel gender_label;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel home_i;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JLabel log_i;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_txt;
    private javax.swing.JLabel phone_label;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JButton save_btn;
    private javax.swing.JLabel save_icon;
    private javax.swing.JComboBox<String> status_combox;
    private javax.swing.JLabel status_label;
    // End of variables declaration//GEN-END:variables
}
