/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nurse;

import hospital_managment_system.Log_In;
import hospital_managment_system.Home;

/**
 *
 * @author Nafiul Alam
 */
public class Nurse extends javax.swing.JFrame {

    /**
     * Creates new form Nurse
     */
    public Nurse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nurse = new javax.swing.JPanel();
        lg_icon2 = new javax.swing.JLabel();
        log_out1 = new javax.swing.JButton();
        view_i1 = new javax.swing.JLabel();
        view_btn1 = new javax.swing.JButton();
        s_icon1 = new javax.swing.JLabel();
        search1 = new javax.swing.JButton();
        d_icon1 = new javax.swing.JLabel();
        delete1 = new javax.swing.JButton();
        u_icon1 = new javax.swing.JLabel();
        update1 = new javax.swing.JButton();
        add_icon1 = new javax.swing.JLabel();
        add1 = new javax.swing.JButton();
        lg_icon1 = new javax.swing.JLabel();
        log_out = new javax.swing.JButton();
        view_i = new javax.swing.JLabel();
        view_btn = new javax.swing.JButton();
        s_icon = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        d_icon = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        u_icon = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        add_icon = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        H_icon = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        page_title_label = new javax.swing.JLabel();
        cover_nurse = new javax.swing.JLabel();
        bg_nurse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nurse");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        Nurse.setPreferredSize(new java.awt.Dimension(1050, 626));
        Nurse.setLayout(null);

        lg_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/system-log-out-icon.png"))); // NOI18N
        Nurse.add(lg_icon2);
        lg_icon2.setBounds(790, 380, 30, 30);

        log_out1.setBackground(new java.awt.Color(153, 153, 153));
        log_out1.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        log_out1.setForeground(new java.awt.Color(51, 51, 51));
        log_out1.setText("log-out");
        log_out1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out1ActionPerformed(evt);
            }
        });
        Nurse.add(log_out1);
        log_out1.setBounds(680, 360, 250, 120);

        view_i1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/view-icon.png"))); // NOI18N
        Nurse.add(view_i1);
        view_i1.setBounds(530, 360, 50, 60);

        view_btn1.setBackground(new java.awt.Color(153, 153, 153));
        view_btn1.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        view_btn1.setForeground(new java.awt.Color(51, 51, 51));
        view_btn1.setText("view");
        view_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btn1ActionPerformed(evt);
            }
        });
        Nurse.add(view_btn1);
        view_btn1.setBounds(430, 360, 250, 120);

        s_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/search-icon.png"))); // NOI18N
        Nurse.add(s_icon1);
        s_icon1.setBounds(290, 360, 48, 60);

        search1.setBackground(new java.awt.Color(153, 153, 153));
        search1.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        search1.setForeground(new java.awt.Color(51, 51, 51));
        search1.setText("search");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        Nurse.add(search1);
        search1.setBounds(200, 360, 230, 120);

        d_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/delete-icon.png"))); // NOI18N
        Nurse.add(d_icon1);
        d_icon1.setBounds(790, 250, 40, 40);

        delete1.setBackground(new java.awt.Color(153, 153, 153));
        delete1.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        delete1.setForeground(new java.awt.Color(51, 51, 51));
        delete1.setText("delete");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        Nurse.add(delete1);
        delete1.setBounds(680, 240, 250, 120);

        u_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/update-icon.png"))); // NOI18N
        Nurse.add(u_icon1);
        u_icon1.setBounds(540, 250, 32, 40);

        update1.setBackground(new java.awt.Color(153, 153, 153));
        update1.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        update1.setForeground(new java.awt.Color(51, 51, 51));
        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        Nurse.add(update1);
        update1.setBounds(430, 240, 250, 120);

        add_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/add-icon.png"))); // NOI18N
        Nurse.add(add_icon1);
        add_icon1.setBounds(300, 250, 40, 40);

        add1.setBackground(new java.awt.Color(153, 153, 153));
        add1.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        add1.setForeground(new java.awt.Color(51, 51, 51));
        add1.setText("Add");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        Nurse.add(add1);
        add1.setBounds(200, 240, 230, 120);

        lg_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/system-log-out-icon.png"))); // NOI18N
        Nurse.add(lg_icon1);
        lg_icon1.setBounds(10, 490, 30, 30);

        log_out.setBackground(new java.awt.Color(153, 153, 153));
        log_out.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        log_out.setForeground(new java.awt.Color(51, 51, 51));
        log_out.setText("log-out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        Nurse.add(log_out);
        log_out.setBounds(0, 470, 180, 70);

        view_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/view-icon.png"))); // NOI18N
        Nurse.add(view_i);
        view_i.setBounds(10, 410, 50, 60);

        view_btn.setBackground(new java.awt.Color(153, 153, 153));
        view_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        view_btn.setForeground(new java.awt.Color(51, 51, 51));
        view_btn.setText("view");
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });
        Nurse.add(view_btn);
        view_btn.setBounds(0, 410, 180, 60);

        s_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/search-icon.png"))); // NOI18N
        Nurse.add(s_icon);
        s_icon.setBounds(10, 350, 48, 60);

        search.setBackground(new java.awt.Color(153, 153, 153));
        search.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(51, 51, 51));
        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        Nurse.add(search);
        search.setBounds(0, 350, 180, 60);

        d_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/delete-icon.png"))); // NOI18N
        Nurse.add(d_icon);
        d_icon.setBounds(8, 294, 40, 50);

        delete.setBackground(new java.awt.Color(153, 153, 153));
        delete.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(51, 51, 51));
        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        Nurse.add(delete);
        delete.setBounds(0, 290, 180, 60);

        u_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/update-icon.png"))); // NOI18N
        Nurse.add(u_icon);
        u_icon.setBounds(10, 240, 40, 40);

        update.setBackground(new java.awt.Color(153, 153, 153));
        update.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(51, 51, 51));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        Nurse.add(update);
        update.setBounds(0, 230, 180, 60);

        add_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/add-icon.png"))); // NOI18N
        Nurse.add(add_icon);
        add_icon.setBounds(10, 180, 30, 40);

        add.setBackground(new java.awt.Color(153, 153, 153));
        add.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        add.setForeground(new java.awt.Color(51, 51, 51));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        Nurse.add(add);
        add.setBounds(0, 170, 180, 60);

        H_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/home-icon.png"))); // NOI18N
        Nurse.add(H_icon);
        H_icon.setBounds(10, 110, 32, 60);

        Home.setBackground(new java.awt.Color(153, 153, 153));
        Home.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(51, 51, 51));
        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        Nurse.add(Home);
        Home.setBounds(0, 110, 180, 60);

        page_title_label.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 36)); // NOI18N
        page_title_label.setForeground(new java.awt.Color(51, 51, 51));
        page_title_label.setText("Nurse Panel");
        Nurse.add(page_title_label);
        page_title_label.setBounds(180, 0, 330, 70);

        cover_nurse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nurse/cover-photo.jpg"))); // NOI18N
        Nurse.add(cover_nurse);
        cover_nurse.setBounds(0, 0, 1050, 70);

        bg_nurse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nurse/bg_nurse.jpg"))); // NOI18N
        bg_nurse.setText("jLabel1");
        Nurse.add(bg_nurse);
        bg_nurse.setBounds(0, 0, 1050, 626);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Nurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Nurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed

        Home h=new Home();
        h.setVisible(true);
        dispose();

    }//GEN-LAST:event_HomeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        add_nurse an=new add_nurse();
        an.setVisible(true);
        dispose();
        

    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        update_nurse un=new update_nurse();
        un.setVisible(true);
        dispose();
        

    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        delete_nurse dn=new delete_nurse();
        dn.setVisible(true);
        dispose();
        

    }//GEN-LAST:event_deleteActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        search_nurse sn=new search_nurse();
        sn.setVisible(true);
        dispose();

    }//GEN-LAST:event_searchActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed

        view_nurse vn=new view_nurse();
        vn.setVisible(true);
        dispose();
    }//GEN-LAST:event_view_btnActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed

        Log_In l=new Log_In();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_log_outActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        // TODO add your handling code here:
        add_nurse an=new add_nurse();
        an.setVisible(true);
        dispose();
        

    }//GEN-LAST:event_add1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        // TODO add your handling code here:
        update_nurse un=new update_nurse();
        un.setVisible(true);
        dispose();
        

    }//GEN-LAST:event_update1ActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        // TODO add your handling code here:
        delete_nurse dn=new delete_nurse();
        dn.setVisible(true);
        dispose();

    }//GEN-LAST:event_delete1ActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
        search_nurse sn=new search_nurse();
        sn.setVisible(true);
        dispose();

    }//GEN-LAST:event_search1ActionPerformed

    private void view_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btn1ActionPerformed
        // TODO add your handling code here:
        view_nurse vn=new view_nurse();
        vn.setVisible(true);
        dispose();

    }//GEN-LAST:event_view_btn1ActionPerformed

    private void log_out1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out1ActionPerformed
        // TODO add your handling code here:

        Log_In l=new Log_In();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_log_out1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nurse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel H_icon;
    private javax.swing.JButton Home;
    private javax.swing.JPanel Nurse;
    private javax.swing.JButton add;
    private javax.swing.JButton add1;
    private javax.swing.JLabel add_icon;
    private javax.swing.JLabel add_icon1;
    private javax.swing.JLabel bg_nurse;
    private javax.swing.JLabel cover_nurse;
    private javax.swing.JLabel d_icon;
    private javax.swing.JLabel d_icon1;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete1;
    private javax.swing.JLabel lg_icon1;
    private javax.swing.JLabel lg_icon2;
    private javax.swing.JButton log_out;
    private javax.swing.JButton log_out1;
    private javax.swing.JLabel page_title_label;
    private javax.swing.JLabel s_icon;
    private javax.swing.JLabel s_icon1;
    private javax.swing.JButton search;
    private javax.swing.JButton search1;
    private javax.swing.JLabel u_icon;
    private javax.swing.JLabel u_icon1;
    private javax.swing.JButton update;
    private javax.swing.JButton update1;
    private javax.swing.JButton view_btn;
    private javax.swing.JButton view_btn1;
    private javax.swing.JLabel view_i;
    private javax.swing.JLabel view_i1;
    // End of variables declaration//GEN-END:variables
}
