/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doctor;

import com.mysql.jdbc.Connection;
import hospital_managment_system.Home;
import hospital_managment_system.Log_In;
import hospital_managment_system.MySqlConnect;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Nafiul Alam
 */
public class add_doctor extends javax.swing.JFrame {

    private Connection conn;
    private PreparedStatement pst;
    
    public add_doctor() {
        initComponents();
    }


public void clear(){
        id_TextField.setText("");
        name_TextField.setText("");
        phone_TextField.setText("");
        email_TextField.setText("");
        age_txt.setText("");
        address_TextField1.setText("");
        Join_Date.setCalendar(null);
        department_combox.setSelectedIndex(0);
        gender_combox.setSelectedIndex(0);
        blood_combox.setSelectedIndex(0);
        status_combox.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_panel_d = new javax.swing.JPanel();
        log_i = new javax.swing.JLabel();
        home_i = new javax.swing.JLabel();
        back_i = new javax.swing.JLabel();
        clear_i = new javax.swing.JLabel();
        save_icon = new javax.swing.JLabel();
        status_label = new javax.swing.JLabel();
        blood_label = new javax.swing.JLabel();
        gender_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        dept_label = new javax.swing.JLabel();
        age_label = new javax.swing.JLabel();
        address_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        phone_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        cancel_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        logOut_btn = new javax.swing.JButton();
        status_combox = new javax.swing.JComboBox<>();
        blood_combox = new javax.swing.JComboBox<>();
        gender_combox = new javax.swing.JComboBox<>();
        Join_Date = new com.toedter.calendar.JDateChooser();
        department_combox = new javax.swing.JComboBox<>();
        age_txt = new javax.swing.JTextField();
        address_TextField1 = new javax.swing.JTextField();
        email_TextField = new javax.swing.JTextField();
        phone_TextField = new javax.swing.JTextField();
        name_TextField = new javax.swing.JTextField();
        id_TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        add_cover_d = new javax.swing.JLabel();
        add_bg_d = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" Add Doctor Panal");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        add_panel_d.setPreferredSize(new java.awt.Dimension(1050, 626));
        add_panel_d.setLayout(null);

        log_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/system-log-out-icon.png"))); // NOI18N
        add_panel_d.add(log_i);
        log_i.setBounds(810, 100, 32, 50);

        home_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/home-icon.png"))); // NOI18N
        add_panel_d.add(home_i);
        home_i.setBounds(650, 100, 32, 50);

        back_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/back-icon.png"))); // NOI18N
        add_panel_d.add(back_i);
        back_i.setBounds(500, 100, 40, 50);

        clear_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/clear-icon.png"))); // NOI18N
        add_panel_d.add(clear_i);
        clear_i.setBounds(680, 474, 32, 30);

        save_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/save-icon.png"))); // NOI18N
        add_panel_d.add(save_icon);
        save_icon.setBounds(840, 470, 32, 40);

        status_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        status_label.setForeground(new java.awt.Color(102, 0, 102));
        status_label.setText("Maritial Status :");
        add_panel_d.add(status_label);
        status_label.setBounds(550, 400, 190, 40);

        blood_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blood_label.setForeground(new java.awt.Color(204, 0, 0));
        blood_label.setText("Blood Group :");
        add_panel_d.add(blood_label);
        blood_label.setBounds(580, 350, 164, 40);

        gender_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gender_label.setForeground(new java.awt.Color(102, 0, 102));
        gender_label.setText("Gender :");
        add_panel_d.add(gender_label);
        gender_label.setBounds(640, 300, 102, 40);

        date_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date_label.setForeground(new java.awt.Color(102, 0, 102));
        date_label.setText("Join Date :");
        add_panel_d.add(date_label);
        date_label.setBounds(610, 250, 140, 40);

        dept_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dept_label.setForeground(new java.awt.Color(102, 0, 102));
        dept_label.setText("Department :");
        add_panel_d.add(dept_label);
        dept_label.setBounds(580, 200, 160, 40);

        age_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        age_label.setForeground(new java.awt.Color(102, 0, 102));
        age_label.setText("Age :");
        add_panel_d.add(age_label);
        age_label.setBounds(120, 450, 70, 40);

        address_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        address_label.setForeground(new java.awt.Color(102, 0, 102));
        address_label.setText("Address :");
        add_panel_d.add(address_label);
        address_label.setBounds(70, 400, 110, 40);

        email_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        email_label.setForeground(new java.awt.Color(102, 0, 102));
        email_label.setText("Email :");
        add_panel_d.add(email_label);
        email_label.setBounds(100, 350, 90, 40);

        phone_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        phone_label.setForeground(new java.awt.Color(102, 0, 102));
        phone_label.setText("Phone :");
        add_panel_d.add(phone_label);
        phone_label.setBounds(90, 300, 100, 40);

        name_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name_label.setForeground(new java.awt.Color(102, 0, 102));
        name_label.setText("Name :");
        add_panel_d.add(name_label);
        name_label.setBounds(100, 250, 90, 40);

        id_label.setBackground(new java.awt.Color(255, 255, 255));
        id_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id_label.setForeground(new java.awt.Color(102, 0, 102));
        id_label.setText("ID :");
        add_panel_d.add(id_label);
        id_label.setBounds(140, 200, 50, 40);

        cancel_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel_btn.setForeground(new java.awt.Color(102, 102, 102));
        cancel_btn.setText("Clear");
        cancel_btn.setToolTipText("Clear");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        add_panel_d.add(cancel_btn);
        cancel_btn.setBounds(670, 460, 150, 60);

        save_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save_btn.setForeground(new java.awt.Color(102, 102, 102));
        save_btn.setText("Save");
        save_btn.setToolTipText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        add_panel_d.add(save_btn);
        save_btn.setBounds(830, 460, 150, 60);

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(102, 102, 102));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        add_panel_d.add(back_btn);
        back_btn.setBounds(480, 90, 160, 70);

        home_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(102, 102, 102));
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        add_panel_d.add(home_btn);
        home_btn.setBounds(640, 90, 160, 70);

        logOut_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOut_btn.setForeground(new java.awt.Color(102, 102, 102));
        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        add_panel_d.add(logOut_btn);
        logOut_btn.setBounds(800, 90, 160, 70);

        status_combox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        status_combox.setForeground(new java.awt.Color(102, 102, 102));
        status_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", " " }));
        add_panel_d.add(status_combox);
        status_combox.setBounds(750, 400, 155, 40);

        blood_combox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blood_combox.setForeground(new java.awt.Color(102, 102, 102));
        blood_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", " ", " " }));
        add_panel_d.add(blood_combox);
        blood_combox.setBounds(750, 350, 155, 40);

        gender_combox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gender_combox.setForeground(new java.awt.Color(102, 102, 102));
        gender_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "FeMale", "Common", " " }));
        add_panel_d.add(gender_combox);
        gender_combox.setBounds(750, 300, 155, 40);

        Join_Date.setDateFormatString("yyyy-MM-dd");
        Join_Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_panel_d.add(Join_Date);
        Join_Date.setBounds(750, 250, 180, 40);

        department_combox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        department_combox.setForeground(new java.awt.Color(102, 102, 102));
        department_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Family Physician", "Gynecologist ", "Neurologist", "Surgeon", "Cardiologist", "Psychiatrist", "Dermatologist", "Nephrologist", "Pediatrician", "Otolaryngologist", "Anesthesiologist", " " }));
        add_panel_d.add(department_combox);
        department_combox.setBounds(750, 200, 220, 40);

        age_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        age_txt.setForeground(new java.awt.Color(51, 51, 51));
        age_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                age_txtKeyPressed(evt);
            }
        });
        add_panel_d.add(age_txt);
        age_txt.setBounds(200, 450, 150, 40);
        add_panel_d.add(address_TextField1);
        address_TextField1.setBounds(200, 400, 310, 40);
        add_panel_d.add(email_TextField);
        email_TextField.setBounds(200, 350, 310, 40);
        add_panel_d.add(phone_TextField);
        phone_TextField.setBounds(200, 300, 310, 40);

        name_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_TextFieldActionPerformed(evt);
            }
        });
        add_panel_d.add(name_TextField);
        name_TextField.setBounds(200, 250, 310, 40);
        add_panel_d.add(id_TextField);
        id_TextField.setBounds(200, 200, 310, 40);

        jLabel1.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Doctor >> Add Panel");
        add_panel_d.add(jLabel1);
        jLabel1.setBounds(60, 10, 510, 40);

        add_cover_d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/cover-photo.jpg"))); // NOI18N
        add_panel_d.add(add_cover_d);
        add_cover_d.setBounds(0, 0, 1050, 70);

        add_bg_d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/bg_home.jpg"))); // NOI18N
        add_panel_d.add(add_bg_d);
        add_bg_d.setBounds(0, 0, 1050, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(add_panel_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(add_panel_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_TextFieldActionPerformed

    private void age_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_txtKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key ==  10){
            department_combox.requestFocus();
        }
    }//GEN-LAST:event_age_txtKeyPressed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        // TODO add your handling code here:
        Log_In l=new Log_In();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        doctor d = new doctor();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        conn = (Connection) MySqlConnect.ConnectDB();
        if(conn != null){
            String id = id_TextField.getText();
            String name = name_TextField.getText();
            String phone = phone_TextField.getText();
            String email = email_TextField.getText();
            String address = address_TextField1.getText();
            int age = Integer.parseInt(age_txt.getText());
            String department = (String) department_combox.getSelectedItem();
            String date = ((JTextField)Join_Date.getDateEditor().getUiComponent()).getText();
            String gender = (String) gender_combox.getSelectedItem();
            String blood = (String) blood_combox.getSelectedItem();
            String status = (String) status_combox.getSelectedItem();
            String sql = "INSERT INTO `doctor` (`ID`, `Name`, `Department`, `Email`,  `Phone`, `Address`, `Age`, `Gender`, `Join Date`, `BG`, `Status`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            try{
                pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.setString(2, name);
                pst.setString(3, department);
                pst.setString(4, email);
                pst.setString(5, phone);
                pst.setString(6, address);
                pst.setInt(7, age);
                pst.setString(8, gender);
                pst.setString(9, date);
                pst.setString(10, blood);
                pst.setString(11, status);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Saved Successfully");

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        clear();
        view_doctor vd= new view_doctor();
        vd.setVisible(true);
        dispose();
    }//GEN-LAST:event_save_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
        id_TextField.setText("");
        name_TextField.setText("");
        phone_TextField.setText("");
        email_TextField.setText("");
        age_txt.setText("");
        address_TextField1.setText("");
        Join_Date.setCalendar(null);
        department_combox.setSelectedIndex(0);
        gender_combox.setSelectedIndex(0);
        blood_combox.setSelectedIndex(0);
        status_combox.setSelectedIndex(0);
    }//GEN-LAST:event_cancel_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Join_Date;
    private javax.swing.JLabel add_bg_d;
    private javax.swing.JLabel add_cover_d;
    private javax.swing.JPanel add_panel_d;
    private javax.swing.JTextField address_TextField1;
    private javax.swing.JLabel address_label;
    private javax.swing.JLabel age_label;
    private javax.swing.JTextField age_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel back_i;
    private javax.swing.JComboBox<String> blood_combox;
    private javax.swing.JLabel blood_label;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JLabel clear_i;
    private javax.swing.JLabel date_label;
    private javax.swing.JComboBox<String> department_combox;
    private javax.swing.JLabel dept_label;
    private javax.swing.JTextField email_TextField;
    private javax.swing.JLabel email_label;
    private javax.swing.JComboBox<String> gender_combox;
    private javax.swing.JLabel gender_label;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel home_i;
    private javax.swing.JTextField id_TextField;
    private javax.swing.JLabel id_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JLabel log_i;
    private javax.swing.JTextField name_TextField;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField phone_TextField;
    private javax.swing.JLabel phone_label;
    private javax.swing.JButton save_btn;
    private javax.swing.JLabel save_icon;
    private javax.swing.JComboBox<String> status_combox;
    private javax.swing.JLabel status_label;
    // End of variables declaration//GEN-END:variables
}
