/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doctor;

import hospital_managment_system.Home;
import hospital_managment_system.Log_In;
import hospital_managment_system.MySqlConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nafiul Alam
 */
public class delete_doctor extends javax.swing.JFrame {
    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;

    /**
     * Creates new form delete_doctor
     */
    public delete_doctor() {
        initComponents();
        fetch_table();
    }
    private void update_table(){
        try{
            String sql = "SELECT * FROM doctor";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            doctor_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void fetch_table(){
        conn = (com.mysql.jdbc.Connection) MySqlConnect.ConnectDB();
        try{
            String sql = "SELECT * FROM doctor";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            doctor_table.setModel(DbUtils.resultSetToTableModel(rs));
            doctor_table.setAutoResizeMode(doctor_table.AUTO_RESIZE_OFF);
            doctor_table.getColumnModel().getColumn(0).setPreferredWidth(68);
            doctor_table.getColumnModel().getColumn(1).setPreferredWidth(187);
            doctor_table.getColumnModel().getColumn(2).setPreferredWidth(120);
            doctor_table.getColumnModel().getColumn(3).setPreferredWidth(33);
            doctor_table.getColumnModel().getColumn(4).setPreferredWidth(53);
            doctor_table.getColumnModel().getColumn(5).setPreferredWidth(185);
            doctor_table.getColumnModel().getColumn(6).setPreferredWidth(110);
            doctor_table.getColumnModel().getColumn(7).setPreferredWidth(90);
            doctor_table.getColumnModel().getColumn(8).setPreferredWidth(80);
            doctor_table.getColumnModel().getColumn(9).setPreferredWidth(40);
            doctor_table.getColumnModel().getColumn(10).setPreferredWidth(58);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delete_doctor_panel = new javax.swing.JPanel();
        delete_i1 = new javax.swing.JLabel();
        delete_i = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        status_txt = new javax.swing.JTextField();
        blood_txt = new javax.swing.JTextField();
        date_txt = new javax.swing.JTextField();
        phone_txt = new javax.swing.JTextField();
        department_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        gender_txt = new javax.swing.JTextField();
        age_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        view_table = new javax.swing.JScrollPane();
        doctor_table = new javax.swing.JTable();
        lg_i = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        home_i = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();
        back_i = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        cover_heading = new javax.swing.JLabel();
        cover_delete = new javax.swing.JLabel();
        bg_delete = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete Doctor panel");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        delete_doctor_panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        delete_doctor_panel.setLayout(null);

        delete_i1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/add-icon.png"))); // NOI18N
        delete_doctor_panel.add(delete_i1);
        delete_i1.setBounds(730, 540, 32, 40);

        delete_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/delete-icon.png"))); // NOI18N
        delete_doctor_panel.add(delete_i);
        delete_i.setBounds(870, 540, 32, 40);

        add_btn.setBackground(new java.awt.Color(153, 153, 153));
        add_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 18)); // NOI18N
        add_btn.setForeground(new java.awt.Color(51, 51, 51));
        add_btn.setText("Add");
        add_btn.setToolTipText("");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        delete_doctor_panel.add(add_btn);
        add_btn.setBounds(720, 530, 140, 60);

        delete_btn.setBackground(new java.awt.Color(153, 153, 153));
        delete_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 18)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(51, 51, 51));
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        delete_doctor_panel.add(delete_btn);
        delete_btn.setBounds(860, 530, 180, 60);
        delete_doctor_panel.add(status_txt);
        status_txt.setBounds(980, 90, 60, 30);
        delete_doctor_panel.add(blood_txt);
        blood_txt.setBounds(940, 90, 40, 30);
        delete_doctor_panel.add(date_txt);
        date_txt.setBounds(860, 90, 80, 30);
        delete_doctor_panel.add(phone_txt);
        phone_txt.setBounds(770, 90, 90, 30);
        delete_doctor_panel.add(department_txt);
        department_txt.setBounds(660, 90, 110, 30);
        delete_doctor_panel.add(address_txt);
        address_txt.setBounds(470, 90, 190, 30);
        delete_doctor_panel.add(gender_txt);
        gender_txt.setBounds(420, 90, 50, 30);
        delete_doctor_panel.add(age_txt);
        age_txt.setBounds(390, 90, 30, 30);

        email_txt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        delete_doctor_panel.add(email_txt);
        email_txt.setBounds(270, 90, 120, 30);
        delete_doctor_panel.add(name_txt);
        name_txt.setBounds(80, 90, 190, 30);
        delete_doctor_panel.add(id_txt);
        id_txt.setBounds(10, 90, 70, 30);

        view_table.setForeground(new java.awt.Color(51, 51, 51));

        doctor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Department", "Email", "Phone", "Address", "Age", "Gender", "Date", "Blood Gr", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctor_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctor_tableMouseClicked(evt);
            }
        });
        view_table.setViewportView(doctor_table);

        delete_doctor_panel.add(view_table);
        view_table.setBounds(10, 120, 1030, 410);

        lg_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/system-log-out-icon.png"))); // NOI18N
        delete_doctor_panel.add(lg_i);
        lg_i.setBounds(880, 20, 32, 50);

        logout_btn.setBackground(new java.awt.Color(153, 153, 153));
        logout_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(51, 51, 51));
        logout_btn.setText("log out");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        delete_doctor_panel.add(logout_btn);
        logout_btn.setBounds(870, 20, 170, 50);

        home_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/home-icon.png"))); // NOI18N
        delete_doctor_panel.add(home_i);
        home_i.setBounds(720, 20, 32, 50);

        home_btn.setBackground(new java.awt.Color(153, 153, 153));
        home_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        home_btn.setForeground(new java.awt.Color(51, 51, 51));
        home_btn.setText("home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        delete_doctor_panel.add(home_btn);
        home_btn.setBounds(710, 20, 160, 50);

        back_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/back-icon.png"))); // NOI18N
        delete_doctor_panel.add(back_i);
        back_i.setBounds(560, 20, 32, 50);

        back_btn.setBackground(new java.awt.Color(153, 153, 153));
        back_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(51, 51, 51));
        back_btn.setText("back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        delete_doctor_panel.add(back_btn);
        back_btn.setBounds(550, 20, 160, 50);

        cover_heading.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 18)); // NOI18N
        cover_heading.setForeground(new java.awt.Color(51, 51, 51));
        cover_heading.setText("doctor panel >> delete doctor");
        delete_doctor_panel.add(cover_heading);
        cover_heading.setBounds(10, 30, 390, 19);

        cover_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/cover-photo.jpg"))); // NOI18N
        delete_doctor_panel.add(cover_delete);
        cover_delete.setBounds(0, 0, 1050, 70);

        bg_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/bg_home.jpg"))); // NOI18N
        delete_doctor_panel.add(bg_delete);
        bg_delete.setBounds(0, 0, 1050, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(delete_doctor_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(delete_doctor_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        doctor d=new doctor();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        Log_In l=new Log_In();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    private void doctor_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctor_tableMouseClicked
        try{
            int row = doctor_table.getSelectedRow();
            String tableClick = (doctor_table.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM doctor WHERE ID = '" + tableClick + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String id = rs.getString("ID");
                id_txt.setText(id);
                String name = rs.getString("Name");
                name_txt.setText(name);
                String email = rs.getString("Email");
                email_txt.setText(email);
                String age = rs.getString("Age");
                age_txt.setText(age);
                String gender = rs.getString("Gender");
                gender_txt.setText(gender);
                String adderss = rs.getString("Address");
                address_txt.setText(adderss);
                String department = rs.getString("Department");
                department_txt.setText(department);
                String phone = rs.getString("Phone");
                phone_txt.setText(phone);
                String date = rs.getString("Join Date");
                date_txt.setText(date);
                String blood = rs.getString("BG");
                blood_txt.setText(blood);
                String status = rs.getString("Status");
                status_txt.setText(status);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_doctor_tableMouseClicked

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        conn = (com.mysql.jdbc.Connection) MySqlConnect.ConnectDB();
        String sql = "DELETE FROM doctor WHERE ID = ?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, id_txt.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
            pst.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        update_table();
        doctor_table.setAutoResizeMode(doctor_table.AUTO_RESIZE_OFF);
        doctor_table.getColumnModel().getColumn(0).setPreferredWidth(68);
        doctor_table.getColumnModel().getColumn(1).setPreferredWidth(187);
        doctor_table.getColumnModel().getColumn(2).setPreferredWidth(120);
        doctor_table.getColumnModel().getColumn(3).setPreferredWidth(33);
        doctor_table.getColumnModel().getColumn(4).setPreferredWidth(53);
        doctor_table.getColumnModel().getColumn(5).setPreferredWidth(185);
        doctor_table.getColumnModel().getColumn(6).setPreferredWidth(110);
        doctor_table.getColumnModel().getColumn(7).setPreferredWidth(90);
        doctor_table.getColumnModel().getColumn(8).setPreferredWidth(80);
        doctor_table.getColumnModel().getColumn(9).setPreferredWidth(40);
        doctor_table.getColumnModel().getColumn(10).setPreferredWidth(58);
    }//GEN-LAST:event_delete_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        add_doctor ad=new add_doctor();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_add_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete_doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField age_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel back_i;
    private javax.swing.JLabel bg_delete;
    private javax.swing.JTextField blood_txt;
    private javax.swing.JLabel cover_delete;
    private javax.swing.JLabel cover_heading;
    private javax.swing.JTextField date_txt;
    private javax.swing.JButton delete_btn;
    private javax.swing.JPanel delete_doctor_panel;
    private javax.swing.JLabel delete_i;
    private javax.swing.JLabel delete_i1;
    private javax.swing.JTextField department_txt;
    private javax.swing.JTable doctor_table;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField gender_txt;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel home_i;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel lg_i;
    private javax.swing.JButton logout_btn;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JTextField status_txt;
    private javax.swing.JScrollPane view_table;
    // End of variables declaration//GEN-END:variables
}
