/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doctor;

import hospital_managment_system.Home;
import hospital_managment_system.Log_In;
import hospital_managment_system.MySqlConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nafiul Alam
 */
public class search_doctor extends javax.swing.JFrame {
    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;

    /**
     * Creates new form search_doctor
     */
    public search_doctor() {
        initComponents();
        fetch_table();
    }
    private void fetch_table(){
        conn = (com.mysql.jdbc.Connection) MySqlConnect.ConnectDB();
        try{
//            conn = Connector.ConnectDB();
            String sql = "SELECT * FROM doctor";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            doctor_table.setModel(DbUtils.resultSetToTableModel(rs));
            doctor_table.setAutoResizeMode(doctor_table.AUTO_RESIZE_OFF);
            doctor_table.getColumnModel().getColumn(0).setPreferredWidth(68);
            doctor_table.getColumnModel().getColumn(1).setPreferredWidth(187);
            doctor_table.getColumnModel().getColumn(2).setPreferredWidth(120);
            doctor_table.getColumnModel().getColumn(3).setPreferredWidth(33);
            doctor_table.getColumnModel().getColumn(4).setPreferredWidth(53);
            doctor_table.getColumnModel().getColumn(5).setPreferredWidth(185);
            doctor_table.getColumnModel().getColumn(6).setPreferredWidth(110);
            doctor_table.getColumnModel().getColumn(7).setPreferredWidth(90);
            doctor_table.getColumnModel().getColumn(8).setPreferredWidth(80);
            doctor_table.getColumnModel().getColumn(9).setPreferredWidth(40);
            doctor_table.getColumnModel().getColumn(10).setPreferredWidth(58);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search_doctor_panel = new javax.swing.JPanel();
        view_table = new javax.swing.JScrollPane();
        doctor_table = new javax.swing.JTable();
        lg_i = new javax.swing.JLabel();
        home_i = new javax.swing.JLabel();
        back_i = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        search_txt = new javax.swing.JTextField();
        cover_heading = new javax.swing.JLabel();
        cover_search = new javax.swing.JLabel();
        bg_search = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Doctor");
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        Search_doctor_panel.setPreferredSize(new java.awt.Dimension(1050, 626));
        Search_doctor_panel.setLayout(null);

        view_table.setForeground(new java.awt.Color(51, 51, 51));

        doctor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Department", "Email", "Phone", "Address", "Age", "Gender", "Date", "Blood Gr", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        view_table.setViewportView(doctor_table);

        Search_doctor_panel.add(view_table);
        view_table.setBounds(10, 162, 1030, 430);

        lg_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/system-log-out-icon.png"))); // NOI18N
        Search_doctor_panel.add(lg_i);
        lg_i.setBounds(880, 110, 32, 50);

        home_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/home-icon.png"))); // NOI18N
        Search_doctor_panel.add(home_i);
        home_i.setBounds(720, 110, 32, 50);

        back_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/back-icon.png"))); // NOI18N
        Search_doctor_panel.add(back_i);
        back_i.setBounds(560, 110, 32, 50);

        logout_btn.setBackground(new java.awt.Color(153, 153, 153));
        logout_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(51, 51, 51));
        logout_btn.setText("log out");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        Search_doctor_panel.add(logout_btn);
        logout_btn.setBounds(870, 110, 170, 50);

        home_btn.setBackground(new java.awt.Color(153, 153, 153));
        home_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        home_btn.setForeground(new java.awt.Color(51, 51, 51));
        home_btn.setText("home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        Search_doctor_panel.add(home_btn);
        home_btn.setBounds(710, 110, 160, 50);

        back_btn.setBackground(new java.awt.Color(153, 153, 153));
        back_btn.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(51, 51, 51));
        back_btn.setText("back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        Search_doctor_panel.add(back_btn);
        back_btn.setBounds(550, 110, 160, 50);

        search_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_txt.setForeground(new java.awt.Color(51, 51, 51));
        search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_txtKeyReleased(evt);
            }
        });
        Search_doctor_panel.add(search_txt);
        search_txt.setBounds(60, 110, 410, 45);

        cover_heading.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 18)); // NOI18N
        cover_heading.setForeground(new java.awt.Color(51, 51, 51));
        cover_heading.setText("doctor panel >> search doctor");
        Search_doctor_panel.add(cover_heading);
        cover_heading.setBounds(10, 30, 400, 19);

        cover_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/cover-photo.jpg"))); // NOI18N
        Search_doctor_panel.add(cover_search);
        cover_search.setBounds(0, 0, 1050, 70);

        bg_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/bg_home.jpg"))); // NOI18N
        Search_doctor_panel.add(bg_search);
        bg_search.setBounds(0, 0, 1050, 626);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Search_doctor_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Search_doctor_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_txtKeyReleased
        conn = (com.mysql.jdbc.Connection) MySqlConnect.ConnectDB();
        try{
            String sql = "SELECT * FROM doctor WHERE Name = ? or ID = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1 , search_txt.getText());
            pst.setString(2, search_txt.getText());
            rs = pst.executeQuery();
            doctor_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_search_txtKeyReleased

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        doctor d=new doctor();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        Log_In l=new Log_In();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Search_doctor_panel;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel back_i;
    private javax.swing.JLabel bg_search;
    private javax.swing.JLabel cover_heading;
    private javax.swing.JLabel cover_search;
    private javax.swing.JTable doctor_table;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel home_i;
    private javax.swing.JLabel lg_i;
    private javax.swing.JButton logout_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JScrollPane view_table;
    // End of variables declaration//GEN-END:variables
}
