/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Patient;

import com.mysql.jdbc.Connection;
import hospital_managment_system.Log_In;
import hospital_managment_system.Home;
import hospital_managment_system.MySqlConnect;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Nafiul Alam
 */
public class add_patient extends javax.swing.JFrame {
    
    private Connection conn;
    private PreparedStatement pst;

    /**
     * Creates new form add_patient
     */
    public add_patient() {
        initComponents();
    }
    private void clear(){
        serialNo_txt.setText("");
        id_txt.setText("");
        Join_Date.setCalendar(null);
        name_txt.setText("");
        age_txt.setText("");
        disease_txt.setText("");
        phone_txt.setText("");
        email_txt.setText("");
        address_txt.setText("");
        gender_combox.setSelectedIndex(0);
        roomNo_txt.setText("");
        blood_combox.setSelectedIndex(0);
        status_combox.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_patient = new javax.swing.JPanel();
        clear_i = new javax.swing.JLabel();
        save_icon = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        status_label = new javax.swing.JLabel();
        status_combox = new javax.swing.JComboBox<>();
        blood_label = new javax.swing.JLabel();
        blood_combox = new javax.swing.JComboBox<>();
        roomNo_label = new javax.swing.JLabel();
        roomNo_txt = new javax.swing.JTextField();
        gender_label = new javax.swing.JLabel();
        gender_combox = new javax.swing.JComboBox<>();
        address_label = new javax.swing.JLabel();
        address_txt = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        phone_label = new javax.swing.JLabel();
        phone_txt = new javax.swing.JTextField();
        disease_label = new javax.swing.JLabel();
        disease_txt = new javax.swing.JTextField();
        age_label = new javax.swing.JLabel();
        age_txt = new javax.swing.JTextField();
        name_label = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        date_label = new javax.swing.JLabel();
        Join_Date = new com.toedter.calendar.JDateChooser();
        id_label = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        serialNo_label = new javax.swing.JLabel();
        serialNo_txt = new javax.swing.JTextField();
        log_i = new javax.swing.JLabel();
        home_i = new javax.swing.JLabel();
        back_i = new javax.swing.JLabel();
        logOut_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        bradcum_label = new javax.swing.JLabel();
        cover_patient = new javax.swing.JLabel();
        bg_patient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Patient");
        setBounds(new java.awt.Rectangle(150, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(1050, 626));
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 626));

        Add_patient.setPreferredSize(new java.awt.Dimension(1050, 626));
        Add_patient.setLayout(null);

        clear_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/clear-icon.png"))); // NOI18N
        Add_patient.add(clear_i);
        clear_i.setBounds(670, 470, 32, 40);

        save_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/save-icon.png"))); // NOI18N
        Add_patient.add(save_icon);
        save_icon.setBounds(820, 470, 32, 40);

        clear_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(102, 102, 102));
        clear_btn.setText("Clear");
        clear_btn.setToolTipText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        Add_patient.add(clear_btn);
        clear_btn.setBounds(660, 460, 150, 60);

        save_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save_btn.setForeground(new java.awt.Color(102, 102, 102));
        save_btn.setText("Save");
        save_btn.setToolTipText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        Add_patient.add(save_btn);
        save_btn.setBounds(810, 460, 150, 60);

        status_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        status_label.setForeground(new java.awt.Color(0, 51, 51));
        status_label.setText("Maritial Status :");
        Add_patient.add(status_label);
        status_label.setBounds(500, 390, 200, 40);

        status_combox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        status_combox.setForeground(new java.awt.Color(102, 102, 102));
        status_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Status", "Single", "Married", "Divorced", "" }));
        Add_patient.add(status_combox);
        status_combox.setBounds(700, 390, 280, 40);

        blood_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blood_label.setForeground(new java.awt.Color(204, 0, 0));
        blood_label.setText("Blood Group :");
        Add_patient.add(blood_label);
        blood_label.setBounds(520, 340, 180, 40);

        blood_combox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        blood_combox.setForeground(new java.awt.Color(102, 102, 102));
        blood_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Blood Group", "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", "", "" }));
        Add_patient.add(blood_combox);
        blood_combox.setBounds(700, 340, 280, 40);

        roomNo_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roomNo_label.setForeground(new java.awt.Color(0, 51, 51));
        roomNo_label.setText("Room No :");
        Add_patient.add(roomNo_label);
        roomNo_label.setBounds(560, 290, 140, 40);

        roomNo_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomNo_txt.setForeground(new java.awt.Color(51, 51, 51));
        roomNo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                roomNo_txtKeyPressed(evt);
            }
        });
        Add_patient.add(roomNo_txt);
        roomNo_txt.setBounds(700, 290, 150, 40);

        gender_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gender_label.setForeground(new java.awt.Color(0, 51, 51));
        gender_label.setText("Gender :");
        Add_patient.add(gender_label);
        gender_label.setBounds(590, 240, 110, 40);

        gender_combox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gender_combox.setForeground(new java.awt.Color(102, 102, 102));
        gender_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "FeMale", "Zhe", "" }));
        Add_patient.add(gender_combox);
        gender_combox.setBounds(700, 240, 280, 40);

        address_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        address_label.setForeground(new java.awt.Color(0, 51, 51));
        address_label.setText("Address :");
        Add_patient.add(address_label);
        address_label.setBounds(580, 190, 120, 40);

        address_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        address_txt.setForeground(new java.awt.Color(51, 51, 51));
        address_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                address_txtKeyPressed(evt);
            }
        });
        Add_patient.add(address_txt);
        address_txt.setBounds(700, 190, 310, 40);

        email_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        email_label.setForeground(new java.awt.Color(0, 51, 51));
        email_label.setText("Email :");
        Add_patient.add(email_label);
        email_label.setBounds(610, 140, 90, 40);

        email_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_txt.setForeground(new java.awt.Color(51, 51, 51));
        email_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                email_txtKeyPressed(evt);
            }
        });
        Add_patient.add(email_txt);
        email_txt.setBounds(700, 140, 310, 40);

        phone_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        phone_label.setForeground(new java.awt.Color(0, 51, 51));
        phone_label.setText("Phone :");
        Add_patient.add(phone_label);
        phone_label.setBounds(70, 440, 100, 40);

        phone_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone_txt.setForeground(new java.awt.Color(51, 51, 51));
        phone_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phone_txtKeyPressed(evt);
            }
        });
        Add_patient.add(phone_txt);
        phone_txt.setBounds(170, 440, 310, 40);

        disease_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        disease_label.setForeground(new java.awt.Color(0, 51, 51));
        disease_label.setText("Disease :");
        Add_patient.add(disease_label);
        disease_label.setBounds(50, 390, 120, 40);

        disease_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        disease_txt.setForeground(new java.awt.Color(51, 51, 51));
        disease_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                disease_txtKeyPressed(evt);
            }
        });
        Add_patient.add(disease_txt);
        disease_txt.setBounds(170, 390, 310, 40);

        age_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        age_label.setForeground(new java.awt.Color(0, 51, 51));
        age_label.setText("Age :");
        Add_patient.add(age_label);
        age_label.setBounds(100, 340, 70, 40);

        age_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        age_txt.setForeground(new java.awt.Color(51, 51, 51));
        age_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                age_txtKeyPressed(evt);
            }
        });
        Add_patient.add(age_txt);
        age_txt.setBounds(170, 340, 150, 40);

        name_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name_label.setForeground(new java.awt.Color(0, 51, 51));
        name_label.setText("Name :");
        Add_patient.add(name_label);
        name_label.setBounds(80, 290, 90, 40);

        name_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name_txt.setForeground(new java.awt.Color(51, 51, 51));
        name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name_txtKeyPressed(evt);
            }
        });
        Add_patient.add(name_txt);
        name_txt.setBounds(170, 290, 310, 40);

        date_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date_label.setForeground(new java.awt.Color(0, 51, 51));
        date_label.setText("Date :");
        Add_patient.add(date_label);
        date_label.setBounds(90, 240, 80, 40);

        Join_Date.setDateFormatString("yyyy-MM-dd");
        Join_Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Add_patient.add(Join_Date);
        Join_Date.setBounds(170, 240, 180, 40);

        id_label.setBackground(new java.awt.Color(255, 255, 255));
        id_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id_label.setForeground(new java.awt.Color(0, 51, 51));
        id_label.setText("ID :");
        Add_patient.add(id_label);
        id_label.setBounds(120, 190, 50, 40);

        id_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id_txt.setForeground(new java.awt.Color(51, 51, 51));
        id_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_txtKeyPressed(evt);
            }
        });
        Add_patient.add(id_txt);
        id_txt.setBounds(170, 190, 310, 40);

        serialNo_label.setBackground(new java.awt.Color(255, 255, 255));
        serialNo_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        serialNo_label.setForeground(new java.awt.Color(0, 51, 51));
        serialNo_label.setText("Serial No :");
        Add_patient.add(serialNo_label);
        serialNo_label.setBounds(40, 140, 130, 40);

        serialNo_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        serialNo_txt.setForeground(new java.awt.Color(51, 51, 51));
        serialNo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serialNo_txtKeyPressed(evt);
            }
        });
        Add_patient.add(serialNo_txt);
        serialNo_txt.setBounds(170, 140, 310, 40);

        log_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/system-log-out-icon.png"))); // NOI18N
        Add_patient.add(log_i);
        log_i.setBounds(830, 10, 32, 60);

        home_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/home-icon.png"))); // NOI18N
        Add_patient.add(home_i);
        home_i.setBounds(670, 10, 32, 60);

        back_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor/back-icon.png"))); // NOI18N
        Add_patient.add(back_i);
        back_i.setBounds(510, 10, 40, 60);

        logOut_btn.setBackground(new java.awt.Color(153, 153, 153));
        logOut_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOut_btn.setForeground(new java.awt.Color(51, 51, 51));
        logOut_btn.setText("Log Out");
        logOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_btnActionPerformed(evt);
            }
        });
        Add_patient.add(logOut_btn);
        logOut_btn.setBounds(820, 10, 160, 60);

        home_btn.setBackground(new java.awt.Color(153, 153, 153));
        home_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(51, 51, 51));
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        Add_patient.add(home_btn);
        home_btn.setBounds(660, 10, 160, 60);

        back_btn.setBackground(new java.awt.Color(153, 153, 153));
        back_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(51, 51, 51));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        Add_patient.add(back_btn);
        back_btn.setBounds(500, 10, 160, 60);

        bradcum_label.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 24)); // NOI18N
        bradcum_label.setForeground(new java.awt.Color(51, 51, 51));
        bradcum_label.setText("Patient Panel >> Add Patient");
        Add_patient.add(bradcum_label);
        bradcum_label.setBounds(10, 0, 480, 70);

        cover_patient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Patient/cover-photo.jpg"))); // NOI18N
        Add_patient.add(cover_patient);
        cover_patient.setBounds(0, 0, 1050, 70);

        bg_patient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Patient/bg-photo.jpg"))); // NOI18N
        bg_patient.setText("jLabel1");
        Add_patient.add(bg_patient);
        bg_patient.setBounds(0, 0, 1050, 626);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Add_patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Add_patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        patient p=new patient();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void logOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_btnActionPerformed
        // TODO add your handling code here:
        Log_In l=new Log_In();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_btnActionPerformed

    private void serialNo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialNo_txtKeyPressed
        int key = evt.getKeyCode();
        if(key == 10){
            serialNo_txt.requestFocus();
        }
    }//GEN-LAST:event_serialNo_txtKeyPressed

    private void id_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            id_txt.requestFocus();
        }
    }//GEN-LAST:event_id_txtKeyPressed

    private void name_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            name_txt.requestFocus();
        }
    }//GEN-LAST:event_name_txtKeyPressed

    private void age_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_txtKeyPressed
        int key = evt.getKeyCode();
        if(key == 10){
            age_txt.requestFocus();
        }
    }//GEN-LAST:event_age_txtKeyPressed

    private void disease_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disease_txtKeyPressed
        int key = evt.getKeyCode();
        if(key == 10){
            disease_txt.requestFocus();
        }
    }//GEN-LAST:event_disease_txtKeyPressed

    private void phone_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            phone_txt.requestFocus();
        }
    }//GEN-LAST:event_phone_txtKeyPressed

    private void email_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            email_txt.requestFocus();
        }
    }//GEN-LAST:event_email_txtKeyPressed

    private void address_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_address_txtKeyPressed
        int key = evt.getKeyCode();
        if(key ==  10){
            address_txt.requestFocus();
        }
    }//GEN-LAST:event_address_txtKeyPressed

    private void roomNo_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomNo_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNo_txtKeyPressed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        conn = (Connection) MySqlConnect.ConnectDB();
        if(conn != null){
            int serialNO = Integer.parseInt(serialNo_txt.getText());
            String id = id_txt.getText();
            String date = ((JTextField)Join_Date.getDateEditor().getUiComponent()).getText();
            String name = name_txt.getText();
            int age = Integer.parseInt(age_txt.getText());
            String disease = disease_txt.getText();
            int phone = Integer.parseInt(phone_txt.getText());
            String email = email_txt.getText();
            String address = address_txt.getText();
            String gender = (String) gender_combox.getSelectedItem();
            String roomNo = roomNo_txt.getText();
            String blood = (String) blood_combox.getSelectedItem();
            String status = (String) status_combox.getSelectedItem();
            String sql = "INSERT INTO `patient` (`Serial`, `ID`, `Date`, `Name`, `Age`, `Disease`,  `Phone`, `Email`, `Address`, `Gender`, `Room`, `BG`, `Status`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            try{
                pst = conn.prepareStatement(sql);
                pst.setInt(1, serialNO);
                pst.setString(2, id);
                pst.setString(3, date);
                pst.setString(4, name);
                pst.setInt(5, age);
                pst.setString(6, disease);
                pst.setInt(7, phone);
                pst.setString(8, email);
                pst.setString(9, address);
                pst.setString(10, gender);
                pst.setString(11, roomNo);
                pst.setString(12, blood);
                pst.setString(13, status);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Saved Successfully!");

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        clear();
        View_patient vp=new View_patient();
        vp.setVisible(true);
        dispose();
    }//GEN-LAST:event_save_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        serialNo_txt.setText("");
        id_txt.setText("");
        Join_Date.setCalendar(null);
        name_txt.setText("");
        age_txt.setText("");
        disease_txt.setText("");
        phone_txt.setText("");
        email_txt.setText("");
        address_txt.setText("");
        gender_combox.setSelectedIndex(0);
        roomNo_txt.setText("");
        blood_combox.setSelectedIndex(0);
        status_combox.setSelectedIndex(0);
    }//GEN-LAST:event_clear_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_patient;
    private com.toedter.calendar.JDateChooser Join_Date;
    private javax.swing.JLabel address_label;
    private javax.swing.JTextField address_txt;
    private javax.swing.JLabel age_label;
    private javax.swing.JTextField age_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel back_i;
    private javax.swing.JLabel bg_patient;
    private javax.swing.JComboBox<String> blood_combox;
    private javax.swing.JLabel blood_label;
    private javax.swing.JLabel bradcum_label;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel clear_i;
    private javax.swing.JLabel cover_patient;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel disease_label;
    private javax.swing.JTextField disease_txt;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_txt;
    private javax.swing.JComboBox<String> gender_combox;
    private javax.swing.JLabel gender_label;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel home_i;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton logOut_btn;
    private javax.swing.JLabel log_i;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_txt;
    private javax.swing.JLabel phone_label;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JLabel roomNo_label;
    private javax.swing.JTextField roomNo_txt;
    private javax.swing.JButton save_btn;
    private javax.swing.JLabel save_icon;
    private javax.swing.JLabel serialNo_label;
    private javax.swing.JTextField serialNo_txt;
    private javax.swing.JComboBox<String> status_combox;
    private javax.swing.JLabel status_label;
    // End of variables declaration//GEN-END:variables
}
